Feature/new ux
novorender/novoweb pull request #122
Opened 2024-08-21 13:01 UTC by nd-novorender

https://trello.com/c/Qa3UFdBr/821-explorer-new-ux-design

2024-08-22 08:30 UTC, nd-novorender commented
@barabadzhi that's a massive PR. If you have ideas on how to make it more manageable - let me know.
Also we probably should merge i18n PR first, because there might be a lot of conflicts.

2024-08-26 13:35 UTC, nd-novorender commented
@barabadzhi branch is synced with `develop`

2024-08-26 13:37 UTC, barabadzhi commented
> branch is synced with `develop`
👍🏼 I'll review it as the first thing on my mornings TODO. 🗒️

2024-08-27 18:44 UTC, barabadzhi requested changes
I have ignored multiple minor issues, typings, etc.
Those are to be fixed in the future updates to this impl.

Issues from local use:
1. No text on the menu items in the expanded version, only icons.
2. Clicking on a functions group opens "Functions" with group expanded, but
clicking on another group does not expand the relevant group nor it creates the new "Functions" view (if no tool was selected).
3. Not all groups are visible in "Functions". For example, clicking "Search" icon requires to scroll in order to get Search in the view.
4. WISHLIST: Ability to expand "Functions" view similar to the tool view (same button as in the new WidgetHeader).

<img width="236" alt="Skjermbilde 2024-08-27 kl  20 44 11" src="https://github.com/user-attachments/assets/1e754414-3954-4b56-8bbd-03f196bc17dc">

2024-08-27 18:44 UTC, barabadzhi commented on src/features/locationHud/locationHud.tsx
> +            alt = "-";
Alternative: `let lon = lat = alt = "-";` 😉

2024-08-27 18:44 UTC, barabadzhi commented on src/features/myLocation/useGoToMyLocation.ts
> +                        msg: "Your position is outside the scene's boundaries.",
Translation?

2024-08-27 18:44 UTC, barabadzhi commented on src/features/newDesign/newDesignPopup.tsx
> +    );
Translation?

2024-08-27 18:44 UTC, barabadzhi commented on src/features/quickAccessMenu/clippingMenu.tsx
> +    // const selectingOrthoPoint = activePicker === Picker.OrthoPlane;
?

2024-08-27 18:44 UTC, barabadzhi commented on src/features/quickAccessMenu/clippingMenu.tsx
> +            </MenuItem> */}
Please, rm or uncomment.

2024-08-27 18:44 UTC, barabadzhi commented on src/features/render/renderSlice.ts
> +    // [118, 134, 146],
?

2024-08-27 18:44 UTC, barabadzhi commented on src/features/render/renderSlice.ts
> +    // [97, 94, 155],
?

2024-08-27 18:44 UTC, barabadzhi commented on src/features/widgetGroupPanel/widgetGroupPanel.tsx
> +                height: open ? `calc(100% - ${theme.spacing(layout.padWidgetsTop ? 9 : 0)})` : undefined,
`calc` is one of the slowest CSS features, we can do without here, just calculate percentage directly:
```height: open ? `${100 - theme.spacing(layout.padWidgetsTop ? 9 : 0)}%` : undefined,```

2024-08-27 18:44 UTC, barabadzhi commented on src/features/widgetGroupPanel/widgetGroupPanel.tsx
> +                        height: `calc(100% - ${theme.spacing(8)})`,
same, direct calculation possible

2024-08-27 18:44 UTC, barabadzhi commented on src/features/widgetGroupPanel/widgetGroupPanel.tsx
> +    // complicated margins/width/heights and wrappers around the panel and svg are all for good shadows
👍🏼

2024-08-27 18:44 UTC, barabadzhi commented on src/features/widgets/widgets.tsx
> +                const top = y === 0 ? "0px" : `calc(((100% - ${gap}) / ${gridSize.height} + ${gap}) * ${y})`;
Can it be simplified omitting `calc` where not absolutely necessary?

2024-08-27 18:44 UTC, barabadzhi commented on src/features/widgets/widgets.tsx
> +                height: `calc(100% - ${theme.spacing(layout.padWidgetsTop ? 18 : 9)})`,
Same

2024-08-27 18:44 UTC, barabadzhi commented on src/slices/explorer/slice.ts
> +    // TODO probably should be stored on the backend instead
Do we have a task for it (not to forget)?

2024-08-28 06:17 UTC, nd-novorender commented on src/features/clippingPlanes/clippingPlaneInteractions.tsx
> +        document.body.appendChild(overlay);
I don't think there is any difference between these two approaches

2024-08-28 06:22 UTC, nd-novorender commented on src/features/widgetGroupPanel/widgetGroupPanel.tsx
> +                        height: `calc(100% - ${theme.spacing(8)})`,
`theme.spacing` is in `px` (final value is `calc(100% - 64px)`) - can it be done without `calc`?

2024-08-28 06:23 UTC, nd-novorender commented on src/features/widgets/widgets.tsx
> +                const top = y === 0 ? "0px" : `calc(((100% - ${gap}) / ${gridSize.height} + ${gap}) * ${y})`;
Again all the calcs combine percentages with px and I'm not aware how to do it without `calc`

2024-08-28 06:31 UTC, nd-novorender commented on src/features/hud/hud.tsx
> +            {/* <NewDesignPopup /> */}
Yes - we roll out new design only for Novorender org for now and it's opt-in. New design popup is supposed to be shown when we force new design on people which is going to happen later

2024-08-28 06:33 UTC, nd-novorender commented on src/features/locationHud/locationHud.tsx
> +            alt = "-";
Doesn't work for me :(
![image](https://github.com/user-attachments/assets/cfaed2ad-7217-4557-a95c-6d3274dd6082)

2024-08-28 06:48 UTC, nd-novorender commented on src/features/widgetGroupPanel/widgetGroupPanel.tsx
> +                height: open ? `calc(100% - ${theme.spacing(layout.padWidgetsTop ? 9 : 0)})` : undefined,
`theme.spacing` returns `px`

2024-08-28 10:14 UTC, barabadzhi approved these changes
LGTM 👍🏼

2024-09-03 12:29 UTC, barabadzhi commented on src/components/widgetHeader.tsx
> +import { mixpanel } from "utils/mixpanel";
Unused? 🤔

2024-09-03 12:31 UTC, barabadzhi commented on src/features/widgetList/widgetList.tsx
> +import { mixpanel } from "utils/mixpanel";
Same?

2024-09-03 12:37 UTC, barabadzhi approved these changes

2024-09-04 06:00 UTC, merged